version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/dockerfile-prod
    ports:
      - 8087:8080
    volumes:
      - ../specs:/specs
      - ../swaggerui:/swaggerui